spring.application.name=sission12Security
server.port=9999
spring.datasource.url=jdbc:postgresql://localhost:5432/sision12securiry
spring.datasource.username=postgres
spring.datasource.password=Vuhao2005@

# câu hình sql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# jwt
jwt.secret-key=haomilosinhraoninhbinhqualamotdieuthuyetvoiw
jwt.expired=900000



# c?u hình cloadi
cloud-name=dqsn1crl0
api-key=527729112526488
api-secret=_slsMpvamydmKOA_Mol3CBUYJK8

#c?u hình kích th??c file g?i lên
# Gi?i h?n dung l??ng t?i ?a cho M?T file upload
spring.servlet.multipart.max-file-size=2MB

# Gi?i h?n dung l??ng t?i ?a cho TOÀN B? request (có th? ch?a nhi?u file)
spring.servlet.multipart.max-request-size=20MB

# Ng??ng dung l??ng ?? quy?t ??nh khi nào file s? ???c ghi ra ??a
# 0B ngh?a là m?i file upload ??u ???c ghi tr?c ti?p ra ??a, không gi? trong RAM
spring.servlet.multipart.file-size-threshold=0B

